[project]
name = "inspect-demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13.1"
dependencies = [
    "inspect-ai>=0.3.111",
    "openai>=1.93.0",
]
